name: Build Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
        with:
          submodules: true
      - name: Build Site
        uses: chabad360/hugo-actions@master
